from  sinse import *
k=kyok(44100)
on=k.create_onp(2)
def wv(fun):
    on.reset()
    fun(f("C0"),0.2)
    k.play([on])
    on.reset()
    fun(f("C1"),0.2)
    k.play([on])
    on.reset()
    fun(f("C2"),0.2)
    k.play([on])
    on.reset()
    fun(f("C3"),0.2)
    k.play([on])
    on.reset()
    fun(f("C4"),0.2)
    k.play([on])
    on.reset()
    fun(f("C5"),0.2)
    k.play([on])
    on.reset()
    fun(f("C6"),0.2)
    k.play([on])
    on.reset()
    fun(f("C7"),0.2)
    k.play([on])
wv(on.sin)
wv(on.nok)
wv(on.tan)
wv(on.san)

wv(on.sintan)
wv(on.noktan)